#!/usr/bin/env python

from distutils.core import setup
from setuptools import find_packages

setup(name='test_avro',
      version='0.1.0',
      description='Autogenerated Python Avro Package',
      author='None',
      packages=find_packages('test_avro', 'test_avro.*')
)
