#!/usr/bin/env python

from setuptools import setup, find_packages

setup(name='test_avro',
      version='0.1.0',
      description='Autogenerated Python Avro Package',
      author='None',
      packages=find_packages()
)
